import os
from pathlib import Path
import numpy as np
import faiss
from sentence_transformers import SentenceTransformer
from openai import OpenAI
from src.processing.chunking import split_text
from config import EMBEDDING_MODEL, RAG_CHUNK_SIZE, RAG_CHUNK_OVERLAP, RAG_TOP_K
from dotenv import load_dotenv
load_dotenv(dotenv_path=Path(__file__).resolve().parents[2] / ".env", encoding="utf-8-sig")

_embedding_model = None


def get_embedding_model():
    """Lazy load the embedding model"""
    global _embedding_model
    if _embedding_model is None:
        print("Loading embedding model...")
        _embedding_model = SentenceTransformer(EMBEDDING_MODEL)
        print("Embedding model loaded successfully")
    return _embedding_model


def build_vector_store(transcript, chunk_size=None, overlap=None):
    """
    Builds FAISS index from transcript.
    
    Args:
        transcript: Full transcript text
        chunk_size: Maximum words per chunk
        overlap: Word overlap between chunks
    
    Returns:
        index: FAISS index
        chunks: list of text chunks
    """
    model = get_embedding_model()

    # Fallbacks to central configurations
    current_chunk_size = chunk_size or RAG_CHUNK_SIZE
    current_overlap = overlap or RAG_CHUNK_OVERLAP

    # Split transcript into chunks
    chunks = split_text(transcript, max_words=current_chunk_size, overlap=current_overlap)
    if not chunks:
        return None, []

    print(f"Created {len(chunks)} chunks for RAG")

    # Generate embeddings
    embeddings = model.encode(chunks, convert_to_numpy=True, show_progress_bar=False)

    # Build FAISS index
    dimension = embeddings.shape[1]
    index = faiss.IndexFlatL2(dimension)
    index.add(embeddings)

    print(f"FAISS index built with {index.ntotal} vectors")

    return index, chunks


def retrieve_chunks(question, index, chunks, top_k=None):
    """
    Retrieves most relevant chunks for a question using semantic search.
    
    Args:
        question: User's question
        index: FAISS index
        chunks: List of text chunks
        top_k: Number of top chunks to retrieve
    
    Returns:
        List of retrieved text chunks
    """
    if index is None or not chunks:
        return []
    
    model = get_embedding_model()
    
    # Encode question
    question_embedding = model.encode([question], convert_to_numpy=True, show_progress_bar=False)

    # Search in FAISS index
    current_top_k = top_k or RAG_TOP_K
    distances, indices = index.search(question_embedding, min(current_top_k, len(chunks)))

    # Retrieve chunks
    retrieved = []
    for i, dist in zip(indices[0], distances[0]):
        if i < len(chunks):
            retrieved.append({
                'text': chunks[i],
                'distance': float(dist),
                'index': int(i)
            })

    return retrieved


def generate_answer(question, index, chunks):
    """
    Generates answer using retrieved context via Groq API (Llama 3.3).
    
    Args:
        question: User's question
        index: FAISS index
        chunks: List of text chunks
    
    Returns:
        Answer string generated by LLM
    """
    top_k = 4  # Fixed medium retrieval depth

    
    # Retrieve relevant chunks
    retrieved_chunks = retrieve_chunks(question, index, chunks, top_k=top_k)

    if not retrieved_chunks:
        return "Not found"

    # Combine retrieved chunks into a single context string
    context = "\n".join([chunk["text"] for chunk in retrieved_chunks])
    
    # Initialize Groq client
    api_key = os.environ.get("GROQ_API_KEY", "YOUR_GROQ_API_KEY")
    client = OpenAI(
        api_key=api_key,
        base_url="https://api.groq.com/openai/v1"
    )
    
    messages = [
        {
            "role": "system",
            "content": "You are an assistant that answers questions from podcast transcripts. Use only the provided context. If the answer is not found, say 'Not found'. Keep answers concise."
        },
        {
            "role": "user",
            "content": f"Context:\n{context}\n\nQuestion:\n{question}\n\nAnswer:"
        }
    ]
    
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=messages,
            temperature=0.3
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"Error generating answer using Groq API: {str(e)}"


def search_transcript(query, index, chunks, top_k=5):
    """
    Simple search function for finding specific information.
    
    Args:
        query: Search query
        index: FAISS index
        chunks: List of text chunks
        top_k: Number of results to return
    
    Returns:
        List of matching chunks with relevance scores
    """
    retrieved = retrieve_chunks(query, index, chunks, top_k=top_k)
    
    results = []
    for chunk_data in retrieved:
        results.append({
            'text': chunk_data['text'],
            'relevance': 1 / (1 + chunk_data['distance'])  # Convert distance to relevance score
        })
    
    return results
